/**
 * KorScan AI - Master Reference Korean Vocabulary Database (Thư Viện Từ Vựng Sách Chuẩn)
 * Expanded Dictionary with 250+ High-Frequency TOPIK & Practical Words
 */

window.KORSCAN_BOOK_VOCAB_DB = [
    // ─── 1. CHÀO HỎI & GIỚI THIỆU (GREETING & INTRO) ───
    { korean: "안녕하세요", romaja: "an-nyeong-ha-se-yo", vietnamese: "Xin chào (Lịch sự)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "안녕하세요! 만나서 반갑습니다." },
    { korean: "안녕하십니까", romaja: "an-nyeong-ha-sip-ni-da", vietnamese: "Xin chào (Trang trọng)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "안녕하십니까? 처음 뵙겠습니다." },
    { korean: "감사합니다", romaja: "gam-sa-ham-ni-da", vietnamese: "Cảm ơn (Trang trọng)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "도와주셔서 감사합니다." },
    { korean: "고맙습니다", romaja: "go-map-seum-ni-da", vietnamese: "Cảm ơn (Lịch sự)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "선물 고맙습니다." },
    { korean: "죄송합니다", romaja: "jwe-song-ham-ni-da", vietnamese: "Xin lỗi (Trang trọng)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "늦어서 죄송합니다." },
    { korean: "미안합니다", romaja: "mi-an-ham-ni-da", vietnamese: "Xin lỗi (Lịch sự)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "미안합니다. 괜찮아요?" },
    { korean: "안녕히 계세요", romaja: "an-nyeong-hi gye-se-yo", vietnamese: "Chào tạm biệt (Ở lại)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "저는 먼저 가볼게요. 안녕히 계세요." },
    { korean: "안녕히 가세요", romaja: "an-nyeong-hi ga-se-yo", vietnamese: "Chào tạm biệt (Đi về)", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "조심히 돌아가세요. 안녕히 가세요." },
    { korean: "반갑습니다", romaja: "ban-gap-seum-ni-da", vietnamese: "Rất vui được gặp bạn", pos: "Tính từ", topic: "greeting", level: "TOPIK 1", example: "만나서 반갑습니다." },
    { korean: "처음 뵙겠습니다", romaja: "cheo-eum boep-ges-seum-ni-da", vietnamese: "Hân hạnh lần đầu gặp", pos: "Cụm từ", topic: "greeting", level: "TOPIK 1", example: "처음 뵙겠습니다. 잘 부탁드립니다." },
    { korean: "이름", romaja: "i-reum", vietnamese: "Tên", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "이름이 무엇입니까?" },
    { korean: "성함", romaja: "seong-ham", vietnamese: "Tên (Kính ngữ)", pos: "Danh từ", topic: "greeting", level: "TOPIK 2", example: "성함이 어떻게 되십니까?" },
    { korean: "직업", romaja: "ji-geop", vietnamese: "Nghề nghiệp", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "당신의 직업은 무엇입니까?" },
    { korean: "국적", romaja: "guk-jeok", vietnamese: "Quốc tịch", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "국적은 베트남입니다." },
    { korean: "베트남", romaja: "be-teu-nam", vietnamese: "Việt Nam", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "저는 베트남 사람입니다." },
    { korean: "한국", romaja: "han-guk", vietnamese: "Hàn Quốc", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "한국어를 공부합니다." },
    { korean: "사람", romaja: "sa-ram", vietnamese: "Người", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "친절한 사람입니다." },
    { korean: "나이", romaja: "na-i", vietnamese: "Tuổi", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "나이가 몇 살이에요?" },
    { korean: "연세", romaja: "yeon-se", vietnamese: "Tuổi (Kính ngữ)", pos: "Danh từ", topic: "greeting", level: "TOPIK 2", example: "할머니 연세가 어떻게 되세요?" },
    { korean: "고향", romaja: "go-hyang", vietnamese: "Quê hương", pos: "Danh từ", topic: "greeting", level: "TOPIK 1", example: "제 고향은 다낭입니다." },

    // ─── 2. ĐỜI SỐNG & THỜI GIAN (DAILY & TIME) ───
    { korean: "오늘", romaja: "o-neul", vietnamese: "Hôm nay", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "오늘 날씨가 매우 좋습니다." },
    { korean: "어제", romaja: "eo-je", vietnamese: "Hôm qua", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "어제 친구를 만났어요." },
    { korean: "내일", romaja: "nae-il", vietnamese: "Ngày mai", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "내일 한국에 갑니다." },
    { korean: "모레", romaja: "mo-re", vietnamese: "Ngày kia", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "모레 시험을 봅니다." },
    { korean: "그저께", romaja: "geu-jeok-kke", vietnamese: "Hôm kia", pos: "Danh từ", topic: "daily", level: "TOPIK 2", example: "그저께 한국에 도착했어요." },
    { korean: "지금", romaja: "ji-geum", vietnamese: "Bây giờ", pos: "Phó từ", topic: "daily", level: "TOPIK 1", example: "지금 몇 시예요?" },
    { korean: "시간", romaja: "si-gan", vietnamese: "Thời gian / Tiếng", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "시간이 있어요?" },
    { korean: "아침", romaja: "a-chim", vietnamese: "Buổi sáng / Bữa sáng", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "아침 식사를 했습니다." },
    { korean: "점심", romaja: "jeom-sim", vietnamese: "Buổi trưa / Bữa trưa", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "점심에 비빔밥을 먹었어요." },
    { korean: "저녁", romaja: "jeo-nyeok", vietnamese: "Buổi tối / Bữa tối", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "저녁에 영화를 볼 거예요." },
    { korean: "밤", romaja: "bam", vietnamese: "Ban đêm", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "밤 10시에 자요." },
    { korean: "새벽", romaja: "sae-byeok", vietnamese: "Rạng sáng", pos: "Danh từ", topic: "daily", level: "TOPIK 2", example: "새벽에 눈이 내렸어요." },
    { korean: "주말", romaja: "ju-mal", vietnamese: "Cuối tuần", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "주말에 보통 무엇을 해요?" },
    { korean: "평일", romaja: "pyeong-il", vietnamese: "Ngày thường", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "평일에는 일합니다." },
    { korean: "집", romaja: "jip", vietnamese: "Nhà", pos: "Danh từ", topic: "daily", level: "TOPIK 1", example: "집에 돌아왔습니다." },
    { korean: "자다", romaja: "ja-da", vietnamese: "Ngủ", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "일찍 자고 일찍 일어납니다." },
    { korean: "일어나다", romaja: "i-reo-na-da", vietnamese: "Thức dậy", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "아침 7시에 일어납니다." },
    { korean: "쉬다", romaja: "swi-da", vietnamese: "Nghỉ ngơi", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "집에서 편하게 쉬어요." },
    { korean: "씻다", romaja: "ssit-da", vietnamese: "Rửa / Tắm rửa", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "손을 깨끗이 씻으세요." },
    { korean: "청소하다", romaja: "cheong-so-ha-da", vietnamese: "Dọn dẹp vệ sinh", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "방을 청소했습니다." },
    { korean: "빨래하다", romaja: "ppal-rae-ha-da", vietnamese: "Giặt quần áo", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "주말에 빨래를 해요." },
    { korean: "요리하다", romaja: "yo-ri-ha-da", vietnamese: "Nấu ăn", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "저녁을 요리하고 있어요." },
    { korean: "운동하다", romaja: "un-dong-ha-da", vietnamese: "Tập thể dục", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "매일 아침 운동합니다." },
    { korean: "산책하다", romaja: "san-chaek-ha-da", vietnamese: "Đi dạo", pos: "Động từ", topic: "daily", level: "TOPIK 1", example: "공원에서 산책해요." },

    // ─── 3. ẨM THỰC & ĂN UỐNG (FOOD & DRINK) ───
    { korean: "음식", romaja: "eum-sik", vietnamese: "Món ăn / Thức ăn", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "한국 음식을 좋아합니다." },
    { korean: "밥", romaja: "bap", vietnamese: "Cơm / Bữa ăn", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "밥을 먹었습니까?" },
    { korean: "물", romaja: "mul", vietnamese: "Nước", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "시원한 물 한 잔 주세요." },
    { korean: "김치", romaja: "gim-chi", vietnamese: "Kimchi", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "김치는 한국의 전통 음식입니다." },
    { korean: "불고기", romaja: "bul-go-gi", vietnamese: "Thịt nướng Bul-gogi", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "불고기가 참 맛있어요." },
    { korean: "비빔밥", romaja: "bi-bim-bap", vietnamese: "Cơm trộn Bibimbap", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "전주 비빔밥을 주문했어요." },
    { korean: "삼겹살", romaja: "sam-gyeop-sal", vietnamese: "Thịt ba chỉ nướng", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "저녁에 삼겹살을 먹었어요." },
    { korean: "떡볶이", romaja: "tteok-bok-ki", vietnamese: "Bánh gạo cay Tteokbokki", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "매콤한 떡볶이가 먹고 싶어요." },
    { korean: "라면", romaja: "ra-myeon", vietnamese: "Mì ăn liền / Rámen", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "매운 라면을 좋아해요." },
    { korean: "치킨", romaja: "chi-kin", vietnamese: "Gà rán", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "맥주와 치킨을 먹었습니다." },
    { korean: "커피", romaja: "keo-pi", vietnamese: "Cà phê", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "아이스 커피 한 잔 주세요." },
    { korean: "차", romaja: "cha", vietnamese: "Trà / Xe hơi", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "녹차를 마십니다." },
    { korean: "식당", romaja: "sik-dang", vietnamese: "Nhà hàng / Quán ăn", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "유명한 식당에 갔습니다." },
    { korean: "카페", romaja: "ka-pe", vietnamese: "Quán Cà phê", pos: "Danh từ", topic: "food", level: "TOPIK 1", example: "카페에서 친구를 만나요." },
    { korean: "맛있다", romaja: "ma-sit-da", vietnamese: "Ngon", pos: "Tính từ", topic: "food", level: "TOPIK 1", example: "이 음식이 정말 맛있네요." },
    { korean: "맛없다", romaja: "ma-seop-da", vietnamese: "Dở / Không ngon", pos: "Tính từ", topic: "food", level: "TOPIK 1", example: "짜고 맛없어요." },
    { korean: "매울다", romaja: "mae-up-da", vietnamese: "Cay", pos: "Tính từ", topic: "food", level: "TOPIK 1", example: "한국 음식이 조금 매워요." },
    { korean: "달다", romaja: "dal-da", vietnamese: "Ngọt", pos: "Tính từ", topic: "food", level: "TOPIK 1", example: "케이크가 달콤하고 맛있어요." },
    { korean: "짜다", romaja: "jja-da", vietnamese: "Mặn", pos: "Tính từ", topic: "food", level: "TOPIK 1", example: "국물이 조금 짜요." },
    { korean: "싱겁다", romaja: "sing-geop-da", vietnamese: "Nhạt", pos: "Tính từ", topic: "food", level: "TOPIK 1", example: "소금을 넣어 드세요." },
    { korean: "먹다", romaja: "meok-da", vietnamese: "Ăn", pos: "Động từ", topic: "food", level: "TOPIK 1", example: "맛있게 드세요." },
    { korean: "마시다", romaja: "ma-si-da", vietnamese: "Uống", pos: "Động từ", topic: "food", level: "TOPIK 1", example: "따뜻한 차를 마십니다." },
    { korean: "주문하다", romaja: "ju-mun-ha-da", vietnamese: "Gọi món / Đặt hàng", pos: "Động từ", topic: "food", level: "TOPIK 1", example: "메뉴판 보고 주문할게요." },
    { korean: "계산하다", romaja: "gye-san-ha-da", vietnamese: "Thanh toán tiền", pos: "Động từ", topic: "food", level: "TOPIK 1", example: "여기 계산해 주세요." },

    // ─── 4. GIAO THÔNG & PHƯƠNG TIỆN (TRANSPORTATION) ───
    { korean: "버스", romaja: "beo-seu", vietnamese: "Xe buýt", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "버스를 타고 학교에 갑니다." },
    { korean: "지하철", romaja: "ji-ha-cheol", vietnamese: "Tàu điện ngầm", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "서울 지하철은 편리합니다." },
    { korean: "택시", romaja: "taek-si", vietnamese: "Xe Taxi", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "급해서 택시를 탔어요." },
    { korean: "비행기", romaja: "bi-haeng-gi", vietnamese: "Máy bay", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "비행기 표를 예매했습니다." },
    { korean: "자전거", romaja: "ja-jeon-geo", vietnamese: "Xe đạp", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "한강에서 자전거를 탔어요." },
    { korean: "오토바이", romaja: "o-to-ba-i", vietnamese: "Xe máy", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "베트남에는 오토바이가 많아요." },
    { korean: "기차", romaja: "gi-cha", vietnamese: "Tàu hỏa", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "KTX 기차를 타고 부산에 가요." },
    { korean: "역", romaja: "yeok", vietnamese: "Ga / Trạm tàu", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "서울역에서 만납시다." },
    { korean: "정류장", romaja: "jeong-ryu-jang", vietnamese: "Trạm dừng (Xe buýt)", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "버스 정류장이 가까워요." },
    { korean: "공항", romaja: "gong-hang", vietnamese: "Sân bay", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "인천국제공항에 도착했어요." },
    { korean: "타다", romaja: "ta-da", vietnamese: "Đi / Lên (xe, tàu)", pos: "Động từ", topic: "transport", level: "TOPIK 1", example: "지하철 2호선을 타세요." },
    { korean: "내리다", romaja: "nae-ri-da", vietnamese: "Xuống (xe, tàu)", pos: "Động từ", topic: "transport", level: "TOPIK 1", example: "다음 역에서 내립니다." },
    { korean: "갈아타다", romaja: "ga-ra-ta-da", vietnamese: "Đổi xe / Chuyển tuyến", pos: "Động từ", topic: "transport", level: "TOPIK 2", example: "신도림역에서 갈아타야 합니다." },
    { korean: "운전하다", romaja: "un-jeon-ha-da", vietnamese: "Lái xe", pos: "Động từ", topic: "transport", level: "TOPIK 1", example: "운전면허증을 취득했습니다." },
    { korean: "교통카드", romaja: "gyo-tong-ka-deu", vietnamese: "Thẻ giao thông", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "교통카드를 충전했습니다." },
    { korean: "길", romaja: "gil", vietnamese: "Con đường", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "길을 물어보았습니다." },
    { korean: "건널목", romaja: "geon-neol-mok", vietnamese: "Lối sang đường", pos: "Danh từ", topic: "transport", level: "TOPIK 2", example: "건널목에서 신호를 기다립니다." },
    { korean: "신호등", romaja: "sin-ho-deung", vietnamese: "Đèn giao thông", pos: "Danh từ", topic: "transport", level: "TOPIK 1", example: "빨간 신호등에 멈추세요." },

    // ─── 5. MUA SẮM & GIÁ CẢ (SHOPPING & PRICES) ───
    { korean: "얼마", romaja: "eol-ma", vietnamese: "Bao nhiêu (giá)", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "이 사과는 얼마예요?" },
    { korean: "원", romaja: "won", vietnamese: "Won (Đơn vị tiền Hàn)", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "만 원입니다." },
    { korean: "비싸다", romaja: "bis-sa-da", vietnamese: "Mắc / Đắt", pos: "Tính từ", topic: "shopping", level: "TOPIK 1", example: "조금 비싸네요. 깎아 주세요." },
    { korean: "싸다", romaja: "ssa-da", vietnamese: "Rẻ", pos: "Tính từ", topic: "shopping", level: "TOPIK 1", example: "가격이 싸고 좋아요." },
    { korean: "가게", romaja: "ga-ge", vietnamese: "Cửa hàng / Tiệm", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "옷 가게에 들어갔습니다." },
    { korean: "시장", romaja: "si-jang", vietnamese: "Chợ", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "전통 시장에서 과일을 샀어요." },
    { korean: "마트", romaja: "ma-teu", vietnamese: "Siêu thị", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "대형 마트에서 장을 봐요." },
    { korean: "백화점", romaja: "baek-hwa-jeom", vietnamese: "Trung tâm thương mại", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "백화점에서 쇼핑했습니다." },
    { korean: "편의점", romaja: "pyeon-ui-jeom", vietnamese: "Cửa hàng tiện lợi 24/7", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "집 앞 편의점에 가요." },
    { korean: "카드", romaja: "ka-deu", vietnamese: "Thẻ thanh toán", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "신용카드로 계산할게요." },
    { korean: "현금", romaja: "hyeon-geum", vietnamese: "Tiền mặt", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "현금 영수증을 주세요." },
    { korean: "영수증", romaja: "yeong-su-jeung", vietnamese: "Hóa đơn thanh toán", pos: "Danh từ", topic: "shopping", level: "TOPIK 2", example: "영수증 지참 시 환불 가능." },
    { korean: "사다", romaja: "sa-da", vietnamese: "Mua", pos: "Động từ", topic: "shopping", level: "TOPIK 1", example: "예쁜 옷을 샀어요." },
    { korean: "팔다", romaja: "pal-da", vietnamese: "Bán", pos: "Động từ", topic: "shopping", level: "TOPIK 1", example: "싱싱한 생선을 팝니다." },
    { korean: "환불하다", romaja: "hwan-bul-ha-da", vietnamese: "Hoàn tiền / Trả hàng", pos: "Động từ", topic: "shopping", level: "TOPIK 2", example: "사이즈가 안 맞아 환불했어요." },
    { korean: "교환하다", romaja: "gyo-hwan-ha-da", vietnamese: "Đổi hàng", pos: "Động từ", topic: "shopping", level: "TOPIK 2", example: "다른 색상으로 교환해 주세요." },
    { korean: "할인", romaja: "ha-rin", vietnamese: "Giảm giá / Sale", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "20% 할인 행사 중입니다." },
    { korean: "옷", romaja: "ot", vietnamese: "Quần áo", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "따뜻한 옷을 입으세요." },
    { korean: "신발", romaja: "sin-bal", vietnamese: "Giày dép", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "편안한 운동화를 신어요." },
    { korean: "가방", romaja: "ga-bang", vietnamese: "Cặp / Túi xách", pos: "Danh từ", topic: "shopping", level: "TOPIK 1", example: "가방이 가볍고 튼튼해요." },

    // ─── 6. TRƯỜNG HỌC & GIÁO DỤC (SCHOOL & EDUCATION) ───
    { korean: "학교", romaja: "hak-gyo", vietnamese: "Trường học", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "학교에서 공부합니다." },
    { korean: "대학교", romaja: "dae-hak-gyo", vietnamese: "Trường Đại học", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "서울대학교에 다니고 있어요." },
    { korean: "학생", romaja: "hak-saeng", vietnamese: "Học sinh / Sinh viên", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "저는 열심히 공부하는 학생입니다." },
    { korean: "선생님", romaja: "seon-saeng-nim", vietnamese: "Thầy / Cô giáo", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "선생님, 질문이 있습니다." },
    { korean: "교수님", romaja: "gyo-su-nim", vietnamese: "Giáo sư", pos: "Danh từ", topic: "school", level: "TOPIK 2", example: "지도교수님을 찾아뵀어요." },
    { korean: "교실", romaja: "gyo-sil", vietnamese: "Phòng học", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "교실이 깨끗하고 넓어요." },
    { korean: "도서관", romaja: "do-seo-gwan", vietnamese: "Thư viện", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "도서관에서 책을 읽어요." },
    { korean: "숙제", romaja: "suk-je", vietnamese: "Bài tập về nhà", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "숙제를 다 끝냈습니다." },
    { korean: "시험", romaja: "si-heom", vietnamese: "Kỳ thi / Bài kiểm tra", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "TOPIK 시험 준비를 해요." },
    { korean: "공부하다", romaja: "gong-bu-ha-da", vietnamese: "Học tập", pos: "Động từ", topic: "school", level: "TOPIK 1", example: "매일 2시간씩 공부합니다." },
    { korean: "배우다", romaja: "bae-u-da", vietnamese: "Học (kiến thức mới)", pos: "Động từ", topic: "school", level: "TOPIK 1", example: "한국 문화를 배웁니다." },
    { korean: "가르치다", romaja: "ga-reu-chi-da", vietnamese: "Dạy học", pos: "Động từ", topic: "school", level: "TOPIK 1", example: "학생들에게 언어를 가르쳐요." },
    { korean: "질문하다", romaja: "jil-mun-ha-da", vietnamese: "Hỏi / Đặt câu hỏi", pos: "Động từ", topic: "school", level: "TOPIK 1", example: "이해 안 되면 질문하세요." },
    { korean: "사전", romaja: "sa-jeon", vietnamese: "Từ điển", pos: "Danh từ", topic: "school", level: "TOPIK 1", example: "사전에서 단어를 찾아봐요." },
    { korean: "전공", romaja: "jeon-gong", vietnamese: "Chuyên ngành học", pos: "Danh từ", topic: "school", level: "TOPIK 2", example: "제 전공은 한국어학입니다." },

    // ─── 7. CÔNG VIỆC & CÔNG SỞ (WORK & BUSINESS) ───
    { korean: "회사", romaja: "hoe-sa", vietnamese: "Công ty", pos: "Danh từ", topic: "work", level: "TOPIK 1", example: "무역 회사에 다니고 있어요." },
    { korean: "회사원", romaja: "hoe-sa-won", vietnamese: "Nhân viên công ty", pos: "Danh từ", topic: "work", level: "TOPIK 1", example: "저는 IT 회사원입니다." },
    { korean: "사무실", romaja: "sa-mu-sil", vietnamese: "Văn phòng làm việc", pos: "Danh từ", topic: "work", level: "TOPIK 1", example: "사무실에서 회의 중입니다." },
    { korean: "회의", romaja: "hoe-ui", vietnamese: "Cuộc họp / Hội nghị", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "오후 2시에 중요한 회의가 있어요." },
    { korean: "출근하다", romaja: "chul-geun-ha-da", vietnamese: "Đi làm", pos: "Động từ", topic: "work", level: "TOPIK 2", example: "매일 아침 8시반에 출근해요." },
    { korean: "퇴근하다", romaja: "toe-geun-ha-da", vietnamese: "Tan làm", pos: "Động từ", topic: "work", level: "TOPIK 2", example: "오늘 6시에 퇴근할 수 있어요." },
    { korean: "야근", romaja: "ya-geun", vietnamese: "Làm tăng ca / Làm đêm", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "프로젝트 때문에 야근을 해야 해요." },
    { korean: "월급", romaja: "wol-geup", vietnamese: "Tiền lương hàng tháng", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "다음 주가 월급날입니다." },
    { korean: "서류", romaja: "seo-ryu", vietnamese: "Hồ sơ / Tài liệu", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "서류를 검토해 주세요." },
    { korean: "보고서", romaja: "bo-go-seo", vietnamese: "Báo cáo", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "주간 보고서를 작성했습니다." },
    { korean: "사장님", romaja: "sa-jang-nim", vietnamese: "Giám đốc / Chủ DN", pos: "Danh từ", topic: "work", level: "TOPIK 1", example: "사장님께서 결재하셨습니다." },
    { korean: "부장님", romaja: "bu-jang-nim", vietnamese: "Trưởng phòng", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "부장님께 지시를 받았습니다." },
    { korean: "동료", romaja: "dong-ryo", vietnamese: "Đồng nghiệp", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "직장 동료들과 사이가 좋아요." },
    { korean: "출장", romaja: "chul-jang", vietnamese: "Đi công tác", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "다음 주에 부산으로 출장을 가요." },
    { korean: "면접", romaja: "myeon-jeop", vietnamese: "Phỏng vấn xin việc", pos: "Danh từ", topic: "work", level: "TOPIK 2", example: "취업 면접을 준비 중입니다." },
    { korean: "취직하다", romaja: "chwi-jik-ha-da", vietnamese: "Xin được việc làm", pos: "Động từ", topic: "work", level: "TOPIK 2", example: "대기업에 취직했습니다." },

    // ─── 8. DU LỊCH & NGHỈ DƯỠNG (TRAVEL & VACATION) ───
    { korean: "여행", romaja: "yeo-haeng", vietnamese: "Du lịch", pos: "Danh từ", topic: "travel", level: "TOPIK 1", example: "제주도로 여행을 떠납니다." },
    { korean: "호텔", romaja: "ho-tel", vietnamese: "Khách sạn", pos: "Danh từ", topic: "travel", level: "TOPIK 1", example: "바다가 보이는 호텔을 예약했어요." },
    { korean: "예약하다", romaja: "ye-yak-ha-da", vietnamese: "Đặt phòng / Đặt chỗ", pos: "Động từ", topic: "travel", level: "TOPIK 1", example: "비행기 표를 미리 예약했어요." },
    { korean: "여권", romaja: "yeo-gwon", vietnamese: "Hộ chiếu (Passport)", pos: "Danh từ", topic: "travel", level: "TOPIK 1", example: "여권 만료일을 확인하세요." },
    { korean: "비자", romaja: "bi-ja", vietnamese: "Thị thực (Visa)", pos: "Danh từ", topic: "travel", level: "TOPIK 1", example: "한국 관광 비자를 신청했습니다." },
    { korean: "지도를 보다", romaja: "ji-do-reul bo-da", vietnamese: "Xem bản đồ", pos: "Cụm từ", topic: "travel", level: "TOPIK 1", example: "지도를 보고 길을 찾았어요." },
    { korean: "관광지", romaja: "gwan-gwang-ji", vietnamese: "Địa điểm tham quan", pos: "Danh từ", topic: "travel", level: "TOPIK 2", example: "유명한 관광지를 방문했어요." },
    { korean: "사진을 찍다", romaja: "sa-jin-eul jjik-da", vietnamese: "Chụp ảnh", pos: "Cụm từ", topic: "travel", level: "TOPIK 1", example: "경치 좋은 곳에서 사진을 찍어요." },
    { korean: "기념품", romaja: "gi-nyeom-pum", vietnamese: "Quà lưu niệm", pos: "Danh từ", topic: "travel", level: "TOPIK 2", example: "친구들을 위해 기념품을 샀어요." },

    // ─── 9. SỨC KHỎE & BỆNH VIỆN (HEALTH & MEDICAL) ───
    { korean: "병원", romaja: "byeong-won", vietnamese: "Bệnh viện", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "배가 아파서 병원에 갔어요." },
    { korean: "약국", romaja: "yak-guk", vietnamese: "Hiệu thuốc", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "약국에서 감기약을 샀습니다." },
    { korean: "의사", romaja: "ui-sa", vietnamese: "Bác sĩ", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "친절한 의사 선생님." },
    { korean: "간호사", romaja: "gan-ho-sa", vietnamese: "Y sĩ / Y tá", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "간호사분이 주사를 놓아주셨어요." },
    { korean: "약", romaja: "yak", vietnamese: "Thuốc", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "식후 30분에 약을 드세요." },
    { korean: "아프다", romaja: "a-peu-da", vietnamese: "Đau / Đau ốm", pos: "Tính từ", topic: "health", level: "TOPIK 1", example: "머리가 많이 아픕니다." },
    { korean: "감기", romaja: "gam-gi", vietnamese: "Bệnh cảm cúm", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "감기에 걸렸어요." },
    { korean: "열", romaja: "yeol", vietnamese: "Cơn sốt / Nhiệt độ", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "열이 나고 몸살이 있어요." },
    { korean: "기침", romaja: "gi-chim", vietnamese: "Cơn ho", pos: "Danh từ", topic: "health", level: "TOPIK 1", example: "기침이 멈추지 않아요." },
    { korean: "치료", romaja: "chi-ryo", vietnamese: "Điều trị / Thăm khám", pos: "Danh từ", topic: "health", level: "TOPIK 2", example: "꾸준한 치료가 필요합니다." },
    { korean: "수술", romaja: "su-sul", vietnamese: "Phẫu thuật", pos: "Danh từ", topic: "health", level: "TOPIK 2", example: "성공적으로 수술을 마쳤습니다." },
    { korean: "건강하다", romaja: "geon-gang-ha-da", vietnamese: "Khỏe mạnh", pos: "Tính từ", topic: "health", level: "TOPIK 1", example: "항상 건강하시길 바랍니다." },

    // ─── 10. THỜI TIẾT & MÙA MÀNG (WEATHER & SEASONS) ───
    { korean: "날씨", romaja: "nal-ssi", vietnamese: "Thời tiết", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "오늘 날씨가 정말 화창합니다." },
    { korean: "비", romaja: "bi", vietnamese: "Mưa", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "밖에는 비가 내리고 있어요." },
    { korean: "눈", romaja: "nun", vietnamese: "Tuyết / Mắt", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "하얀 눈이 내립니다." },
    { korean: "바람", romaja: "ba-ram", vietnamese: "Gió", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "바람이 불어 시원해요." },
    { korean: "구름", romaja: "gu-reum", vietnamese: "Mây", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "하늘에 구름이 많아요." },
    { korean: "태양", romaja: "tae-yang", vietnamese: "Mặt trời", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "태양이 뜨겁게 내리쬐요." },
    { korean: "덥다", romaja: "deop-da", vietnamese: "Nóng", pos: "Tính từ", topic: "weather", level: "TOPIK 1", example: "여름은 날씨가 매우 덥습니다." },
    { korean: "춥다", romaja: "chup-da", vietnamese: "Lạnh", pos: "Tính từ", topic: "weather", level: "TOPIK 1", example: "겨울은 추우니까 따뜻하게 입으세요." },
    { korean: "따뜻하다", romaja: "tta-tteut-ha-da", vietnamese: "Ấm áp", pos: "Tính từ", topic: "weather", level: "TOPIK 1", example: "봄 날씨가 따뜻합니다." },
    { korean: "시원하다", romaja: "si-won-ha-da", vietnamese: "Mát mẻ", pos: "Tính từ", topic: "weather", level: "TOPIK 1", example: "바람이 불어서 시원해요." },
    { korean: "봄", romaja: "bom", vietnamese: "Mùa xuân", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "봄에는 꽃이 피어 예쁩니다." },
    { korean: "여름", romaja: "yeo-reum", vietnamese: "Mùa hè", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "여름 방학에 바다로 갑니다." },
    { korean: "가을", romaja: "ga-eul", vietnamese: "Mùa thu", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "가을은 단풍이 아름다운 계절입니다." },
    { korean: "겨울", romaja: "gyeo-ul", vietnamese: "Mùa đông", pos: "Danh từ", topic: "weather", level: "TOPIK 1", example: "겨울에는 스키를 탑니다." },

    // ─── 11. CẢM XÚC & TÍNH CÁCH (EMOTION & PERSONALITY) ───
    { korean: "기쁘다", romaja: "gi-ppeu-da", vietnamese: "Vui mừng / Hân hoan", pos: "Tính từ", topic: "emotion", level: "TOPIK 1", example: "합격해서 정말 기쁩니다." },
    { korean: "슬프다", romaja: "seul-peu-da", vietnamese: "Buồn bã", pos: "Tính từ", topic: "emotion", level: "TOPIK 1", example: "슬픈 영화를 보고 울었어요." },
    { korean: "행복하다", romaja: "haeng-bok-ha-da", vietnamese: "Hạnh phúc", pos: "Tính từ", topic: "emotion", level: "TOPIK 1", example: "가족과 함께 있어서 행복합니다." },
    { korean: "화나다", romaja: "hwa-na-da", vietnamese: "Tức giận", pos: "Động từ", topic: "emotion", level: "TOPIK 2", example: "약속을 안 지켜서 화가 났어요." },
    { korean: "걱정하다", romaja: "geok-jeong-ha-da", vietnamese: "Lo lắng", pos: "Động từ", topic: "emotion", level: "TOPIK 2", example: "너무 걱정하지 마세요." },
    { korean: "심심하다", romaja: "sim-sim-ha-da", vietnamese: "Buồn chán / Rảnh rỗi", pos: "Tính từ", topic: "emotion", level: "TOPIK 1", example: "할 일이 없어서 심심해요." },
    { korean: "피곤하다", romaja: "pi-gon-ha-da", vietnamese: "Mệt mỏi", pos: "Tính từ", topic: "emotion", level: "TOPIK 1", example: "일이 많아서 피곤합니다." },
    { korean: "친절하다", romaja: "chin-jeol-ha-da", vietnamese: "Thân thiện / Thâm thúy", pos: "Tính từ", topic: "emotion", level: "TOPIK 1", example: "주인분이 참 친절하세요." },
    { korean: "솔직하다", romaja: "sol-jik-ha-da", vietnamese: "Thành thật / Thẳng thắn", pos: "Tính từ", topic: "emotion", level: "TOPIK 2", example: "솔직하게 표현하는 편이에요." }
];
